# Generated by Django 5.2.8 on 2025-12-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employees_count', models.PositiveIntegerField()),
                ('external_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='buildings', to='building.organization'),
        ),
    ]
